# ####################################### #
# 此文件是本項目的主配置文件，所有配置將被應用 #
# ####################################### #
# 服務器的配置
server:
  # Servlet（Java用於處理請求的組件）的配置
  servlet:
    # 編碼配置
    encoding:
      # 強制使用指定的編碼
      force: true
      # 字符集
      charset: UTF-8

# Spring的配置
spring:
  # Profile的配置
  profiles:
    # 激活哪些Profile配置
    active: dev
  # Jackson框架的配置
  jackson:
    # 響應的JSON結果中默認包含什麼樣的屬性
    default-property-inclusion: non_null
  # WEB配置
  web:
    # 靜態資源配置
    resources:
      #靜態資源文件夾，如果多個應使用英文逗號隔開，本地路徑必須使用 file: 作為前綴(全覆蓋模式)
      static-locations: classpath:static, file:${tea-store.upload.root-dir-name}

# MyBatis Plus配置
mybatis-plus:
  # 配置SQL語句的XML文件的位置
  mapper-locations: classpath:mappers/**/*.xml

# Knife4j配置
knife4j:
  # 開啓增強模式
  enable: true
